manifest = "31f8305046461b64c69a6353dbc3beaeec74f7e419dedd34ac1799a43132e9aa"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function_types"
target = "//:function-types"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type-traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "4392ed19b232ed2dde7623843d7e30ef669d860e"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "branch=master" ]
revision = "e8b834a93f7ba935aa63a3d6690804f3bd2b0963"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "branch=master" ]
revision = "fd648b89c18430fa4cb3622018cc99ba99412ffe"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "branch=master" ]
revision = "a1873af9c1d31fb8ec2a87482b6bb9729439b4ac"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "branch=master" ]
revision = "4d01d0f9c0ae3ae3cd20e3cbfddbc9909ce8e064"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "branch=master" ]
revision = "4d0a507c0d1a1011c5a98d57acc9f6b755141e4f"
